### ISSUE TITLE
모든 API 엔드포인트에 타입 힌트 명시하기

### ISSUE THREAD

**Issue by Sungchul-P** [Sungchul-P/learn-fastapi#7]
- 엔드포인트 혹은 함수 코드의 가독성을 높이기 위해 입,출력에 대한 타입 힌트를 명시해줘야 한다.

**Comment by heumsi** [comment]
이건 그대로 진행해주시면 되겠습니다.

**Comment by Sungchul-P** [comment]
#12

**Comment by Sungchul-P** [comment]
[PR #12] refactor: API 엔드포인트 반환 값 타입힌트 추가
